<?xml version="1.0"?>
<package format="2">
  <name>nav_driver</name>
  <version>3.4.1</version>
  <description>Navigation driver with exploration and object approach</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>roscpp</depend>
  <depend>actionlib</depend>
  <depend>move_base_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>tf2</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>tf</depend>
  <depend>dynamic_reconfigure</depend>
  <depend>teb_local_planner</depend>
  <depend>std_srvs</depend>

  <exec_depend>move_base</exec_depend>
  <exec_depend>global_planner</exec_depend>
  <exec_depend>clear_costmap_recovery</exec_depend>
  <exec_depend>rotate_recovery</exec_depend>
  <exec_depend>costmap_converter</exec_depend>
  <exec_depend>rviz</exec_depend>
  <exec_depend>roslaunch</exec_depend>
  <exec_depend>ultralytics_8_4_47</exec_depend>
</package>
