#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""Create a wall-connected version of a ROS occupancy-grid PGM map.

This script is intentionally conservative: it keeps the original free space
and only draws a small set of manually selected wall segments. It is useful
when a map is already navigation-friendly, but major wall boundaries are
broken by sparse SLAM points.
"""

from __future__ import print_function

import argparse
import os
import shutil
import sys

import numpy as np


def strip_roslaunch_args(argv):
    return [arg for arg in argv if ":=" not in arg]


def read_pgm(path):
    with open(path, "rb") as f:
        magic = f.readline().strip()
        if magic != b"P5":
            raise ValueError("Only binary P5 PGM is supported: %s" % path)
        line = f.readline()
        while line.startswith(b"#"):
            line = f.readline()
        width, height = [int(v) for v in line.split()]
        maxval = int(f.readline().strip())
        if maxval > 255:
            raise ValueError("Only 8-bit PGM is supported")
        data = np.frombuffer(f.read(), dtype=np.uint8)
    if data.size != width * height:
        raise ValueError("PGM data size mismatch")
    return data.reshape((height, width)).copy()


def write_pgm(path, image):
    height, width = image.shape
    with open(path, "wb") as f:
        f.write(b"P5\n")
        f.write(("# generated by manual_wall_connect_map.py\n").encode("ascii"))
        f.write(("%d %d\n255\n" % (width, height)).encode("ascii"))
        f.write(image.astype(np.uint8).tobytes())


def draw_line(image, x1, y1, x2, y2, value=0, thickness=1):
    """Draw a Bresenham line in image coordinates."""
    x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
    dx = abs(x2 - x1)
    dy = -abs(y2 - y1)
    sx = 1 if x1 < x2 else -1
    sy = 1 if y1 < y2 else -1
    err = dx + dy
    x, y = x1, y1
    radius = max(0, int(thickness) // 2)
    height, width = image.shape
    while True:
        for yy in range(y - radius, y + radius + 1):
            for xx in range(x - radius, x + radius + 1):
                if 0 <= xx < width and 0 <= yy < height:
                    image[yy, xx] = value
        if x == x2 and y == y2:
            break
        e2 = 2 * err
        if e2 >= dy:
            err += dy
            x += sx
        if e2 <= dx:
            err += dx
            y += sy


def default_my_map_cropped_segments():
    """Segments selected for the 137x115 my_map_cropped map.

    Coordinates are image pixels with origin at the top-left of the PGM.
    They correspond to the red wall-continuation strokes marked in the user's
    screenshot: left boundary, upper/lower corridor walls, central short wall,
    lower short wall, and right vertical wall.
    """
    return [
        (2, 45, 2, 80),
        (2, 46, 63, 46),
        (2, 79, 62, 79),
        (65, 34, 65, 43),
        (64, 80, 64, 104),
        (84, 4, 84, 114),
    ]


def default_my_map_cropped_clear_rects():
    """Small cleanup rectangles that turn overdrawn corner protrusions white."""
    return [
        (64, 45, 70, 51),
        (63, 74, 70, 79),
    ]


def default_my_map_cropped_noise_rects():
    """User-selected local noise patches to clear without global filtering."""
    return [
        (47, 48, 61, 50),
        (58, 75, 64, 77),
        (66, 98, 69, 106),
        (79, 98, 83, 106),
        (67, 35, 69, 40),
        (52, 75, 57, 77),
        (66, 82, 70, 95),
    ]


def default_my_map_cropped_wall_fill_rects():
    """Small wall patches used to complete selected 90-degree corners."""
    return [
        (62, 42, 65, 47),
    ]


def copy_yaml(input_yaml, output_yaml, output_pgm):
    if not input_yaml:
        return
    with open(input_yaml, "rb") as f:
        text = f.read().decode("utf-8")
    image_name = os.path.basename(output_pgm)
    lines = []
    replaced = False
    for line in text.splitlines():
        if line.strip().startswith("image:"):
            lines.append("image: %s" % image_name)
            replaced = True
        else:
            lines.append(line)
    if not replaced:
        lines.insert(0, "image: %s" % image_name)
    with open(output_yaml, "wb") as f:
        f.write(("\n".join(lines) + "\n").encode("utf-8"))


def parse_segment(text):
    parts = [int(v.strip()) for v in text.split(",")]
    if len(parts) != 4:
        raise argparse.ArgumentTypeError("segment must be x1,y1,x2,y2")
    return tuple(parts)


def build_arg_parser():
    parser = argparse.ArgumentParser(description="Connect selected wall gaps on a ROS PGM map.")
    parser.add_argument("--input-pgm", required=True)
    parser.add_argument("--input-yaml", default=None)
    parser.add_argument("--output-prefix", required=True)
    parser.add_argument("--preset", default="my_map_cropped", choices=["my_map_cropped", "none"])
    parser.add_argument("--segment", action="append", type=parse_segment, default=[],
                        help="extra wall segment in image pixels: x1,y1,x2,y2")
    parser.add_argument("--thickness", type=int, default=2)
    parser.add_argument("--no-corner-cleanup", action="store_true",
                        help="disable preset cleanup of overdrawn 90-degree corners")
    parser.add_argument("--clear-selected-noise", action="store_true",
                        help="clear only the preset local noise patches selected for my_map_cropped")
    return parser


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]
    argv = strip_roslaunch_args(argv)
    args = build_arg_parser().parse_args(argv)

    image = read_pgm(args.input_pgm)
    segments = []
    wall_fill_rects = []
    noise_rects = []
    if args.preset == "my_map_cropped":
        if not args.no_corner_cleanup:
            for x1, y1, x2, y2 in default_my_map_cropped_clear_rects():
                image[y1:y2 + 1, x1:x2 + 1] = 254
        wall_fill_rects.extend(default_my_map_cropped_wall_fill_rects())
        if args.clear_selected_noise:
            noise_rects.extend(default_my_map_cropped_noise_rects())
        segments.extend(default_my_map_cropped_segments())
    segments.extend(args.segment)

    for segment in segments:
        draw_line(image, segment[0], segment[1], segment[2], segment[3],
                  value=0, thickness=args.thickness)
    for x1, y1, x2, y2 in wall_fill_rects:
        image[y1:y2 + 1, x1:x2 + 1] = 0
    for x1, y1, x2, y2 in noise_rects:
        image[y1:y2 + 1, x1:x2 + 1] = 254

    output_pgm = args.output_prefix + ".pgm"
    output_yaml = args.output_prefix + ".yaml"
    out_dir = os.path.dirname(output_pgm)
    if out_dir and not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    write_pgm(output_pgm, image)
    if args.input_yaml:
        copy_yaml(args.input_yaml, output_yaml, output_pgm)
    print("Wrote %s" % output_pgm)
    if args.input_yaml:
        print("Wrote %s" % output_yaml)


if __name__ == "__main__":
    main()
